#!/bin/bash

llamafactory-cli train \
    --stage sft \
    --do_train True \
    --model_name_or_path ./saves/targeted_safety_alignment \
    --preprocessing_num_workers 16 \
    --finetuning_type freeze \
    --template default \
    --flash_attn auto \
    --dataset_dir ./data \
    --dataset alpaca_code_train \
    --cutoff_len 2048 \
    --learning_rate 1e-5 \
    --num_train_epochs 3.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 10 \
    --save_steps 100 \
    --warmup_steps 40 \
    --packing False \
    --report_to none \
    --output_dir ./saves/downstream_code \
    --bf16 True \
    --plot_loss True \
    --trust_remote_code True \
    --ddp_timeout 180000000 \
    --include_num_input_tokens_seen True \
    --optim adamw_torch \
    --freeze_layers_start 2 \
    --freeze_layers_end 18 \
    --freeze_trainable_modules all \
    --deepspeed examples/deepspeed/ds_z2_config.json